[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"
requires-python = "==3.9"

[project]
name = "antelop"
authors = [{name = "Rory Bedford", email = "rbedford@mrc-lmb.cam.ac.uk"}]
dynamic = ["version", "description"]
